default: &default
  adapter: postgres
  database: til
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: til-test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: til
  pool: 5
  timeout: 5000

production:
  pool: 75
  timeout: 5000

